### PR TITLE
Bump reportlab from 3.5.67 to 3.6.3

### PR DESCRIPTION
**Pull request by benthorner**
https://www.pivotaltracker.com/story/show/180421592

Changelog: https://fossies.org/linux/reportlab/CHANGES.md

All changes look minor, no cause for concern.

### CODE REVIEW

**Comment by benthorner** [comment]
Visual testing completed as per [the guidance](https://github.com/alphagov/notifications-template-preview/blob/222071338ecd41754f58a3457b9888795de9ffcc/docs/deploying.md#changes-to-pdf-generation). While the changes are minor, the library is used in lots of places in our precompiled letter code, so we may as well be cautious with the deployment, as per the guidance.

**Review by klssmith — APPROVED** [review]

**Comment by benthorner** [comment]
Analysis complete for validation errors. Nothing new during the deployment window. There was an increased number of "content-outside-of-printable-area" areas, but I'm satisfied that's just part of the overall elevated number of such errors we saw throughout that day. No more investigation needed.

Still waiting for letters to come through as delivered.

**Comment by benthorner** [comment]
All letters have now been delivered - looks like there was [a little delay](https://govuk.zendesk.com/agent/tickets/4809584) but no longer.

**Comment by benthorner** [comment]
Ironically updating this package doesn't fix the security alert, which actually affects all versions of the package. I'm not sure why the alert is listed twice, but apparently:

> In order to reduce risk, use trustedSchemes & trustedHosts (see in Reportlab's documentation)

I don't think we use the HTML conversion parts of reportlab - we use `weasyprint` for templated letters. I think we could just silence this alert, but ideally we should investigate it thoroughly.

This does raise the question of whether to merge this change at all. Ideally we should keep this dependency up-to-date as it's a major one for this app. On the other hand, the upgrade adds no value and may yet incur an impact.

**Comment by benthorner** [comment]
@klssmith what do you think?

Maybe one for @idavidmcdonald to comment on too (as it's a risk management kind of thing).

**Comment by klssmith** [comment]
I think it would be nice to bump anyway, just to try and avoid us getting back in the state where everything is really out of date. I'd be a bit more comfortable waiting until January to do it though - over the Christmas period we're expecting a lot of letters, they won't be processed on the bank holidays (so will build up a bit) plus there will be fewer people around if anything goes wrong - waiting a couple of weeks feels a bit safer. I'll leave it up to @idavidmcdonald to make the final call though

**Comment by idavidmcdonald** [comment]
I'm happy to go with your suggestion @klssmith , thanks!

**Pull request merged**
