### PR TITLE
Updated the base version from bullseye 3.9-slim-bullseye to bookworm 3.9.18-slim-bookworm

### PR DESCRIPTION
**Pull request by robbrazil**
Modified dependencies versions

### CODE REVIEW

**Comment by robbrazil** [comment]
Latest local test run:
================================== test session starts ===================================
platform linux -- Python 3.9.18, pytest-7.1.3, pluggy-1.3.0
rootdir: /home/vcap/app, configfile: pytest.ini, testpaths: tests
plugins: mock-3.8.2, forked-1.6.0, requests-mock-1.10.0, xdist-2.5.0, env-0.6.2
gw0 [210] / gw1 [210] / gw2 [210] / gw3 [210] / gw4 [210] / gw5 [210]
.................................................................................. [ 39%]
.................................................................................. [ 78%]
..............................................                                     [100%]
================================== 210 passed in 16.27s ==================================

**Comment by robbrazil** [comment]
That visual testing has a `git cherry-pick -n 41f6e4605c405c37d64aa4a3160f604f948f8536` that is causing conflicts. @klssmith is reviewing that first and we will retake this test once the issue is sorted

**Comment by klssmith** [comment]
I've updated the commit which was being used to test (https://github.com/alphagov/notifications-template-preview/pull/777) so we can take another look now

**Comment by samuelhwilliams** [comment]
@robbrazil how are we getting on with this?

**Comment by idavidmcdonald** [comment]
We didn't make much progress and were struggling to figure out testing the changes and figuring out what differences were acceptable. For that reason we moved it into blocked on our trello board and we need to figure out the next steps...

**Pull request closed without merging**
